# volumes:
services:
    fastapi:
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
        environment:
            MONGO_URL: ${MONGO_URL}
            SIGNING_KEY: ${SIGNING_KEY}
            NUTRITIONIX_ID: ${NUTRITIONIX_ID}
            NUTRITIONIX_KEY: ${NUTRITIONIX_KEY}
            NUTRITIONIX_API_URL: ${NUTRITIONIX_API_URL}
            REACT_URL: ${REACT_URL}
            WAIT_HOSTS: mongo:27017
            WAIT_BEFORE: 5
            WAIT_TIMEOUT: 60

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: ${PUBLIC_URL}
            REACT_APP_API_HOST: ${REACT_APP_API_HOST}
            REACT_APP_SAMPLE_SERVICE_API_HOST: ${REACT_APP_SAMPLE_SERVICE_API_HOST}

    mongo:
        image: mongo
        volumes:
            - ./setup/mongodb:/docker-entrypoint-initdb.d
            - mongodb_data:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

volumes:
    mongodb_data:
        external: true
