# volumes:
services:
    fastapi:
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
        environment:
            MONGO_URL: mongodb://root:password@mongo
            SIGNING_KEY: qm4og5yazi53mwa97imwj6c7usf4a8nmtgxhv2ws
            WAIT_HOSTS: mongo:27017
            WAIT_BEFORE: 5
            WAIT_TIMEOUT: 60

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:3000
            REACT_APP_ACCOUNTS_HOST: http://localhost:8000
            # REACT_APP_SAMPLE_SERVICE_API_HOST: ${REACT_APP_SAMPLE_SERVICE_API_HOST}

    mongo:
        image: mongo
        volumes:
            - ./setup/mongodb:/docker-entrypoint-initdb.d
            - mongodb_data:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

volumes:
    mongodb_data:
        external: true
